 <!-- Js Plugins -->
 <script src="{{ URL::asset('FrontEnd/Templete2/js/jquery-3.3.1.min.js') }}"></script>
 <script src="{{ URL::asset('FrontEnd/Templete2/js/bootstrap.min.js') }}"></script>
 <script src="{{ URL::asset('FrontEnd/Templete2/js/jquery.nice-select.min.js') }}"></script>
 <script src="{{ URL::asset('FrontEnd/Templete2/js/jquery.nicescroll.min.js') }}"></script>
 <script src="{{ URL::asset('FrontEnd/Templete2/js/jquery.magnific-popup.min.js') }}"></script>
 <script src="{{ URL::asset('FrontEnd/Templete2/js/jquery.countdown.min.js') }}"></script>
 <script src="{{ URL::asset('FrontEnd/Templete2/js/jquery.slicknav.js') }}"></script>
 <script src="{{ URL::asset('FrontEnd/Templete2/js/mixitup.min.js') }}"></script>
 <script src="{{ URL::asset('FrontEnd/Templete2/js/owl.carousel.min.js') }}"></script>
 <script src="{{ URL::asset('FrontEnd/Templete2/js/main.js') }}"></script>
