
    <!-- jquery plugins here-->
    <script src="{{ URL::asset('FrontEnd/Templete1/js/jquery-1.12.1.min.js') }}"></script>
    <!-- popper js -->
    <script src="{{ URL::asset('FrontEnd/Templete1/js/popper.min.js') }}"></script>
    <!-- bootstrap js -->
    <script src="{{ URL::asset('FrontEnd/Templete1/js/bootstrap.min.js') }}"></script>
    <!-- easing js -->
    <script src="{{ URL::asset('FrontEnd/Templete1/js/jquery.magnific-popup.js') }}"></script>
    <!-- swiper js -->
    <script src="{{ URL::asset('FrontEnd/Templete1/js/swiper.min.js') }}"></script>
    <!-- swiper js -->
    <script src="{{ URL::asset('FrontEnd/Templete1/js/masonry.pkgd.js') }}"></script>
    <!-- particles js -->
    <script src="{{ URL::asset('FrontEnd/Templete1/js/owl.carousel.min.js') }}"></script>
    <script src="{{ URL::asset('FrontEnd/Templete1/js/jquery.nice-select.min.js') }}"></script>
    <!-- slick js -->
    <script src="{{ URL::asset('FrontEnd/Templete1/js/slick.min.js') }}"></script>
    <script src="{{ URL::asset('FrontEnd/Templete1/js/jquery.counterup.min.js') }}"></script>
    <script src="{{ URL::asset('FrontEnd/Templete1/js/waypoints.min.js') }}"></script>
    <script src="{{ URL::asset('FrontEnd/Templete1/js/contact.js') }}"></script>
    <script src="{{ URL::asset('FrontEnd/Templete1/js/jquery.ajaxchimp.min.js') }}"></script>
    <script src="{{ URL::asset('FrontEnd/Templete1/js/jquery.form.js') }}"></script>
    <script src="{{ URL::asset('FrontEnd/Templete1/js/jquery.validate.min.js') }}"></script>
    <script src="{{ URL::asset('FrontEnd/Templete1/js/mail-script.js') }}"></script>
    <!-- custom js -->
    <script src="{{ URL::asset('FrontEnd/Templete1/js/theme.js') }}"></script>
    <script src="{{ URL::asset('FrontEnd/Templete1/js/custom.js') }}"></script>